baseURL = "https://jimmychancc.github.io/"
languageCode = "en-us"
theme = "anubis2"
title = "Jimmy Chan's Blog" 

[params.author]
name = "Jimmy Chan"
email = "jimmy000701@gmail.com"
location = "Taiwan"

[params]
readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true
locale = "en-us"
math = false # true: enable mathjax globally (default is false)
toc = true

[markup.goldmark.renderer]
unsafe = true # true | false; Enable unsafe mode to have a better experience

[markup.highlight]
style = 'base16-snazzy' # Chroma style, find more at here: https://swapoff.org/chroma/playground/
